# cardless bridge service load balancer
kind: Service
apiVersion: v1
metadata:
  name: cardless-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: cardless-service