# Description : cards-backend micro service 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-newplatform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cards-newplatform
  template:
    metadata:
      labels:
        app: cards-newplatform
    spec:
      containers:
        - name: cards-newplatform
          image: gcr.io/lbgretailpocs/cards-new-platform:latest
          ports:
            - containerPort: 9093
          imagePullPolicy: Always

